# Generated by Django 3.0 on 2019-12-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('serial', models.CharField(max_length=64, unique=True)),
                ('fw_version', models.CharField(max_length=64)),
                ('dev_model', models.CharField(max_length=64)),
            ],
        ),
    ]
